<?php
/**
 * @file
 * site_pages.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function site_pages_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  array(
    \'vid\' => \'1\',
    \'uid\' => \'1\',
    \'title\' => \'Home Page\',
    \'log\' => \'\',
    \'status\' => \'1\',
    \'comment\' => \'1\',
    \'promote\' => \'0\',
    \'sticky\' => \'0\',
    \'vuuid\' => \'ac5b5497-f433-4b17-a153-521f639a3d78\',
    \'nid\' => \'1\',
    \'type\' => \'page\',
    \'language\' => \'und\',
    \'created\' => \'1328246955\',
    \'changed\' => \'1328391042\',
    \'tnid\' => \'0\',
    \'translate\' => \'0\',
    \'uuid\' => \'1372a375-7eac-4029-9eb8-e2a3d27969c5\',
    \'revision_timestamp\' => \'1328391042\',
    \'revision_uid\' => \'1\',
    \'body\' => array(
      \'und\' => array(
        \'0\' => array(
          \'value\' => \'<div style="width: 668px">
<img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box2-top.jpg" />
<div style="width: 638px; float: left; background-image: url(\\\'sites/default/files/box2-center.jpg\\\'); margin: 0; padding: 15px; background-repeat: repeat-y;">
  <div style="width: 399px; float: left; margin: 0;" class="text">
    <b>Test</b>

    SAIVA (South Asians’ International Volunteer Association) is a non-profit group aimed at promoting well-being, education and friendship through volunteering. 

   We focus on enabling seniors to participate in the communities where they live either on a temporary or permanent basis. SAIVA aims to empower South Asians to be active participants in the communities in which they live around the world. 
   SAIVA members actively gain information on community services and volunteer opportunities while identifying ways of sharing and engaging in such opportunities.

   <div class="text3">
     <img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box5-top.jpg" />
     <div style="width: 389px; margin: 0; padding: 5px; float: left; background-image: url(\\\'sites/default/files/box5-center.jpg\\\');"> 
       <img style="margin: 0; padding: 0;" src="sites/default/files/activities-head.jpg" /> 
       <div style="padding: 5px;">
         <b>Friendship:</b> Weekly workshops, Monthly Appreciation Lunches, Annual Picnics, Days or Service, Community Volunteering

         <b>Education:</b> Computer Classes, Yoga/Meditation sessions, Volunteer opportunities at Any Baby Can, Recording for the Blind & Dyslexic, Communities in Schools etc. to support education

         <b>Well-Being:</b> Health screening camps, Bone Marrow registries, Well-being workshops, Self-awareness & Healthy Relationships workshops
       </div>
     </div>
     <img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box5-bottom.jpg" />
   </div>

  </div>
  <img style="float: right; margin: 0; padding: 0" src="sites/default/files/main-image.jpg" />
</div>
<img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box2-bottom.jpg" />
</div>\',
          \'summary\' => \'\',
          \'format\' => \'full_html\',
          \'safe_value\' => \'<div style="width: 668px">
<img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box2-top.jpg" /><div style="width: 638px; float: left; background-image: url(\\\'sites/default/files/box2-center.jpg\\\'); margin: 0; padding: 15px; background-repeat: repeat-y;">
<div style="width: 399px; float: left; margin: 0;" class="text">
    <b>Test</b>
<p>    SAIVA (South Asians’ International Volunteer Association) is a non-profit group aimed at promoting well-being, education and friendship through volunteering. </p>
<p>   We focus on enabling seniors to participate in the communities where they live either on a temporary or permanent basis. SAIVA aims to empower South Asians to be active participants in the communities in which they live around the world.<br />
   SAIVA members actively gain information on community services and volunteer opportunities while identifying ways of sharing and engaging in such opportunities.</p>
<div class="text3">
     <img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box5-top.jpg" /><div style="width: 389px; margin: 0; padding: 5px; float: left; background-image: url(\\\'sites/default/files/box5-center.jpg\\\');">
       <img style="margin: 0; padding: 0;" src="sites/default/files/activities-head.jpg" /><div style="padding: 5px;">
         <b>Friendship:</b> Weekly workshops, Monthly Appreciation Lunches, Annual Picnics, Days or Service, Community Volunteering
<p>         <b>Education:</b> Computer Classes, Yoga/Meditation sessions, Volunteer opportunities at Any Baby Can, Recording for the Blind &amp; Dyslexic, Communities in Schools etc. to support education</p>
<p>         <b>Well-Being:</b> Health screening camps, Bone Marrow registries, Well-being workshops, Self-awareness &amp; Healthy Relationships workshops
       </p></div>
</div>
<p>     <img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box5-bottom.jpg" /></p></div>
</div>
<p>  <img style="float: right; margin: 0; padding: 0" src="sites/default/files/main-image.jpg" /></p></div>
<p><img style="margin: 0; padding: 0; float: left; clear: both;" src="sites/default/files/box2-bottom.jpg" /></p></div>
\',
          \'safe_summary\' => \'\',
        ),
      ),
    ),
    \'field_box2_top\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'12\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'668\',
          \'height\' => \'46\',
          \'uid\' => \'1\',
          \'filename\' => \'box2-top.jpg\',
          \'uri\' => \'public://box2-top.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'3640\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'be3e1567-8e21-4bd9-aba8-917d3ff20b89\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_box2_center\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'13\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'668\',
          \'height\' => \'3\',
          \'uid\' => \'1\',
          \'filename\' => \'box2-center.jpg\',
          \'uri\' => \'public://box2-center.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'396\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'02dea9d5-ca96-4469-af84-007c95e11819\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_box5_top\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'14\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'399\',
          \'height\' => \'11\',
          \'uid\' => \'1\',
          \'filename\' => \'box5-top.jpg\',
          \'uri\' => \'public://box5-top.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'433\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'214e2351-6e07-48d5-a7a0-bc48580af61c\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_box5_center\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'15\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'399\',
          \'height\' => \'4\',
          \'uid\' => \'1\',
          \'filename\' => \'box5-center.jpg\',
          \'uri\' => \'public://box5-center.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'354\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'d5a5b10b-6aab-47ca-8c3d-9ea9e318a506\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_box5_bottom\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'16\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'399\',
          \'height\' => \'8\',
          \'uid\' => \'1\',
          \'filename\' => \'box5-bottom.jpg\',
          \'uri\' => \'public://box5-bottom.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'383\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'e8dff1be-1593-48ae-9f61-62d9b9c4772d\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_activities_head\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'17\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'278\',
          \'height\' => \'27\',
          \'uid\' => \'1\',
          \'filename\' => \'activities-head.jpg\',
          \'uri\' => \'public://activities-head.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'1694\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'b229bff2-2b8a-4090-bdf0-97561cc3d16d\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_box2_bottom\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'18\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'668\',
          \'height\' => \'6\',
          \'uid\' => \'1\',
          \'filename\' => \'box2-bottom.jpg\',
          \'uri\' => \'public://box2-bottom.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'374\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'78c7a93c-f2a0-4021-8c72-338600a1617f\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'field_main_image\' => array(
      \'und\' => array(
        \'0\' => array(
          \'fid\' => \'19\',
          \'alt\' => \'\',
          \'title\' => \'\',
          \'width\' => \'227\',
          \'height\' => \'362\',
          \'uid\' => \'1\',
          \'filename\' => \'main-image.jpg\',
          \'uri\' => \'public://main-image.jpg\',
          \'filemime\' => \'image/jpeg\',
          \'filesize\' => \'34191\',
          \'status\' => \'1\',
          \'timestamp\' => \'1328275105\',
          \'uuid\' => \'e5165e43-070a-4f0e-99e6-2602dadd3d54\',
          \'rdf_mapping\' => array(),
        ),
      ),
    ),
    \'rdf_mapping\' => array(
      \'rdftype\' => array(
        \'0\' => \'foaf:Document\',
      ),
      \'title\' => array(
        \'predicates\' => array(
          \'0\' => \'dc:title\',
        ),
      ),
      \'created\' => array(
        \'predicates\' => array(
          \'0\' => \'dc:date\',
          \'1\' => \'dc:created\',
        ),
        \'datatype\' => \'xsd:dateTime\',
        \'callback\' => \'date_iso8601\',
      ),
      \'changed\' => array(
        \'predicates\' => array(
          \'0\' => \'dc:modified\',
        ),
        \'datatype\' => \'xsd:dateTime\',
        \'callback\' => \'date_iso8601\',
      ),
      \'body\' => array(
        \'predicates\' => array(
          \'0\' => \'content:encoded\',
        ),
      ),
      \'uid\' => array(
        \'predicates\' => array(
          \'0\' => \'sioc:has_creator\',
        ),
        \'type\' => \'rel\',
      ),
      \'name\' => array(
        \'predicates\' => array(
          \'0\' => \'foaf:name\',
        ),
      ),
      \'comment_count\' => array(
        \'predicates\' => array(
          \'0\' => \'sioc:num_replies\',
        ),
        \'datatype\' => \'xsd:integer\',
      ),
      \'last_activity\' => array(
        \'predicates\' => array(
          \'0\' => \'sioc:last_activity_date\',
        ),
        \'datatype\' => \'xsd:dateTime\',
        \'callback\' => \'date_iso8601\',
      ),
    ),
    \'cid\' => \'0\',
    \'last_comment_timestamp\' => \'1328246955\',
    \'last_comment_name\' => NULL,
    \'last_comment_uid\' => \'1\',
    \'comment_count\' => \'0\',
    \'name\' => \'admin\',
    \'picture\' => \'0\',
    \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
    \'path\' => array(
      \'pid\' => \'1\',
      \'source\' => \'node/1\',
      \'alias\' => \'home\',
      \'language\' => \'und\',
    ),
    \'menu\' => array(
      \'link_title\' => \'\',
      \'mlid\' => 0,
      \'plid\' => 0,
      \'menu_name\' => \'main-menu\',
      \'weight\' => 0,
      \'options\' => array(),
      \'module\' => \'menu\',
      \'expanded\' => 0,
      \'hidden\' => 0,
      \'has_children\' => 0,
      \'customized\' => 0,
      \'parent_depth_limit\' => 8,
      \'description\' => \'\',
      \'enabled\' => 1,
    ),
    \'node_export_drupal_version\' => \'7\',
    \'#_export_node_encode_object\' => \'1\',
  ),
)',
);
  return $node_export;
}
